name: Moku Moku

on:
  push:
    branches: [ master ]
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Post Message
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: 'curl -H "Content-Type: application/json" -X POST -d {"username": "もくもく会", "content": "hello"} ${WEBHOOK_URL}'
