name: Moku Moku

on:
  push:
    branches: [ master ]
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Post Message
      run: 'curl -H "Content-Type: application/json" -X POST -d "{\"username\": \"もくもく\", \"content\": \"hello\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}'
