name: Docker Build

on:
  push:
  release:
    types: [published]

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: skyblue3350/github-action-test
    - name: setup qemu
      uses: docker/setup-qemu-action@v1
    - name: install buildx
      uses: docker/setup-buildx-action@v1
    - name: login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.ACCESS_TOKEN }}
    - name: build & push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: ghcr.io/${{ steps.docker_meta.outputs.tags }}
        outputs: type=registry
