name: Docker Build

on:
  push:
  release:
    types: [published]

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install buildx
      uses: docker/setup-buildx-action@v1
    - name: build
      run: docker build .
