name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3

    steps:
    - uses: actions/checkout@master

    - name: install package
      run: pip install yamllint

    - name: lint yaml
      run: yamllint .
