name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test1"

  lint:
    needs: test1
    runs-on: ubuntu-latest
    container: python:3

    steps:
    - uses: actions/checkout@master

    - name: install package
      run: pip install yamllint

    - name: lint yaml
      run: yamllint .

  test2:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: hoge
        run: echo "test2"
